-- Private in-product notifications for the active hiring loop.

create table public.user_notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  notification_type text not null check (
    notification_type in (
      'application_received',
      'application_status_changed',
      'application_withdrawn'
    )
  ),
  title text not null check (char_length(title) between 2 and 160),
  body text not null check (char_length(body) between 2 and 500),
  href text not null check (
    char_length(href) between 2 and 500
    and href like '/%'
  ),
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index user_notifications_user_created_at_idx
on public.user_notifications (user_id, created_at desc);

create index user_notifications_unread_idx
on public.user_notifications (user_id, created_at desc)
where read_at is null;

alter table public.user_notifications enable row level security;

create policy "Users can read their own notifications"
on public.user_notifications
for select
to authenticated
using (user_id = (select auth.uid()));

create policy "Users can mark their own notifications as read"
on public.user_notifications
for update
to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

revoke all on table public.user_notifications from public, anon, authenticated;
grant select on table public.user_notifications to authenticated;
grant update (read_at) on table public.user_notifications to authenticated;

create or replace function private.notify_application_received()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.user_notifications (
    user_id,
    notification_type,
    title,
    body,
    href
  )
  select
    organization_members.user_id,
    'application_received',
    'New application received',
    new.candidate_first_name || ' ' || new.candidate_last_name ||
      ' applied for ' || new.job_title || '.',
    '/dashboard/applications/' || new.id::text
  from public.organization_members
  where organization_members.organization_id = new.organization_id
    and organization_members.role in ('owner', 'admin', 'recruiter');

  return new;
end;
$$;

create or replace function private.notify_application_status_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  status_label text;
begin
  if new.status is not distinct from old.status then
    return new;
  end if;

  if new.status = 'withdrawn' then
    insert into public.user_notifications (
      user_id,
      notification_type,
      title,
      body,
      href
    )
    select
      organization_members.user_id,
      'application_withdrawn',
      'Application withdrawn',
      new.candidate_first_name || ' ' || new.candidate_last_name ||
        ' withdrew their application for ' || new.job_title || '.',
      '/dashboard/applications/' || new.id::text
    from public.organization_members
    where organization_members.organization_id = new.organization_id
      and organization_members.role in ('owner', 'admin', 'recruiter');

    return new;
  end if;

  status_label := case new.status
    when 'submitted' then 'Submitted'
    when 'reviewing' then 'Under review'
    when 'interview' then 'Interview'
    when 'offer' then 'Offer'
    when 'rejected' then 'Not selected'
    else initcap(new.status::text)
  end;

  insert into public.user_notifications (
    user_id,
    notification_type,
    title,
    body,
    href
  )
  values (
    new.candidate_id,
    'application_status_changed',
    'Application status updated',
    new.job_title || ' at ' || new.organization_name ||
      ' is now ' || status_label || '.',
    '/dashboard/applications/' || new.id::text
  );

  return new;
end;
$$;

revoke all on function private.notify_application_received() from public, anon, authenticated;
revoke all on function private.notify_application_status_change() from public, anon, authenticated;

create trigger applications_notify_received
after insert on public.applications
for each row execute function private.notify_application_received();

create trigger applications_notify_status_change
after update of status on public.applications
for each row execute function private.notify_application_status_change();

comment on table public.user_notifications is
  'Private in-product notifications generated by trusted marketplace events.';
