"use client"

import Link from "next/link"
import { CheckCircle2, Download, Plus, Save, Trash2 } from "lucide-react"
import { useState } from "react"

import { saveResume } from "@/app/dashboard/resumes/actions"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import type { ResumeExportAccess } from "@/lib/resume/export-access"
import { cvTemplates, type CvTemplateKey, type ResumeContent, type ResumeEntry } from "@/lib/resume/types"

const lines = (value: string) => value.split("\n").map((line) => line.trim()).filter(Boolean)
const blankEntry = (): ResumeEntry => ({ id: crypto.randomUUID(), title: "", organization: "", location: "", startDate: "", endDate: "", details: "" })

export function ResumeEditor({ exportAccess, initialContent, initialTemplateKey, resumeId, title: initialTitle }: { exportAccess: ResumeExportAccess; initialContent: ResumeContent; initialTemplateKey: CvTemplateKey; resumeId: string; title: string }) {
  const [content, setContent] = useState(initialContent)
  const [title, setTitle] = useState(initialTitle)
  const [templateKey, setTemplateKey] = useState<CvTemplateKey>(initialTemplateKey)
  const set = (field: keyof ResumeContent, value: string) => setContent((current) => ({ ...current, [field]: value }))
  const updateEntry = (section: "experience" | "education", id: string, field: keyof ResumeEntry, value: string) => setContent((current) => ({ ...current, [section]: current[section].map((entry) => entry.id === id ? { ...entry, [field]: value } : entry) }))
  const removeEntry = (section: "experience" | "education", id: string) => setContent((current) => ({ ...current, [section]: current[section].filter((entry) => entry.id !== id) }))
  const addEntry = (section: "experience" | "education") => setContent((current) => ({ ...current, [section]: [...current[section], blankEntry()] }))

  return <div>
    <div className="flex flex-wrap items-start justify-between gap-4 print:hidden">
      <div><Link className="text-sm font-semibold text-primary hover:underline" href="/dashboard/resumes">← My CVs</Link><p className="mt-5 text-xs font-bold tracking-[0.14em] text-primary uppercase">SM VIA CV Builder</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.05em]">Build a healthcare CV that stands out.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Choose an original, U.S.-appropriate layout and build a clear record of your clinical background. CVs never include a photo.</p></div>
      <div className="flex gap-2"><Button disabled={!exportAccess.allowed} onClick={() => window.print()} type="button" variant="outline"><Download/>Download PDF</Button><Button form="resume-form" type="submit"><Save/>Save CV</Button></div>
    </div>

    <div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950 print:hidden"><strong>Early Access:</strong> saving and PDF export are currently free. If paid export is introduced later, pricing will be shown before checkout and your drafts will remain intact.</div>
    <div className="mt-5 grid gap-4 rounded-xl border bg-white p-5 text-sm leading-6 print:hidden md:grid-cols-3"><TemplatePoint title="Clear at a glance">Name, role target, location, and professional contact details.</TemplatePoint><TemplatePoint title="Healthcare-first">Licensure, certifications, and clinical skills appear before experience.</TemplatePoint><TemplatePoint title="Private by design">Do not add a photo, age, gender, marital status, SSN, or references.</TemplatePoint></div>
    <section className="mt-5 rounded-xl border bg-white p-5 print:hidden"><div><p className="text-xs font-bold tracking-[0.14em] text-primary uppercase">Choose a CV template</p><h2 className="mt-1 text-xl font-semibold">Seven original professional layouts</h2><p className="mt-1 text-sm text-muted-foreground">The content stays the same; your selected layout changes how it is presented in the PDF.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cvTemplates.map((template) => <button className={`rounded-xl border p-4 text-left transition ${templateKey === template.key ? "border-primary bg-primary/5 ring-1 ring-primary" : "hover:border-primary/40"}`} key={template.key} onClick={() => setTemplateKey(template.key)} type="button"><span className={`mb-3 block h-2 rounded-full ${templatePreviewClass(template.key)}`}/><strong className="block text-sm">{template.name}</strong><span className="mt-1 block text-xs leading-5 text-muted-foreground">{template.description}</span></button>)}</div></section>

    <div className="mt-7 grid gap-7 xl:grid-cols-[minmax(0,1fr)_minmax(34rem,0.92fr)]">
      <form action={saveResume} className="grid gap-5 print:hidden" id="resume-form"><input name="resumeId" type="hidden" value={resumeId}/><input name="content" type="hidden" value={JSON.stringify(content)}/><input name="templateKey" type="hidden" value={templateKey}/>
        <EditorSection title="Document"><Field label="Résumé name"><Input maxLength={120} onChange={(event) => setTitle(event.target.value)} required value={title}/></Field><input name="title" type="hidden" value={title}/></EditorSection>
        <EditorSection title="Professional identity"><div className="grid gap-4 sm:grid-cols-2"><Field label="Full name"><Input maxLength={120} onChange={(event) => set("fullName", event.target.value)} placeholder="Jordan Lee, RN" value={content.fullName}/></Field><Field label="Professional headline"><Input maxLength={120} onChange={(event) => set("professionalHeadline", event.target.value)} placeholder="Critical Care Registered Nurse" value={content.professionalHeadline}/></Field><Field label="City, State"><Input maxLength={120} onChange={(event) => set("cityState", event.target.value)} placeholder="Chicago, IL" value={content.cityState}/></Field><Field label="Phone"><Input maxLength={30} onChange={(event) => set("phone", event.target.value)} placeholder="(312) 555-0142" value={content.phone}/></Field><Field label="Professional email"><Input maxLength={160} onChange={(event) => set("email", event.target.value)} type="email" value={content.email}/></Field><Field label="LinkedIn URL (optional)"><Input maxLength={300} onChange={(event) => set("linkedin", event.target.value)} type="url" value={content.linkedin}/></Field></div></EditorSection>
        <EditorSection title="Professional summary"><Textarea maxLength={1200} onChange={(event) => set("summary", event.target.value)} placeholder="Write 2–4 concise lines: years of experience, specialty, credentials, and the type of role you are pursuing." rows={5} value={content.summary}/></EditorSection>
        <div className="grid gap-5 sm:grid-cols-2"><EditorSection title="Licensure"><Textarea maxLength={3000} onChange={(event) => set("licenses", event.target.value)} placeholder={"Registered Nurse — Illinois, active\nCompact RN License — active"} rows={5} value={content.licenses}/></EditorSection><EditorSection title="Certifications"><Textarea maxLength={3000} onChange={(event) => set("certifications", event.target.value)} placeholder={"BLS — American Heart Association\nACLS — American Heart Association"} rows={5} value={content.certifications}/></EditorSection></div>
        <EditorSection title="Core clinical skills"><Textarea maxLength={3000} onChange={(event) => set("skills", event.target.value)} placeholder={"Critical care nursing\nPatient assessment\nEpic EHR\nInterdisciplinary care coordination"} rows={6} value={content.skills}/><p className="text-xs leading-5 text-muted-foreground">One clinical, technical, or workflow skill per line. Prioritize skills used in the role you want.</p></EditorSection>
        <EntriesEditor entries={content.experience} label="Professional experience" onAdd={() => addEntry("experience")} onRemove={(id) => removeEntry("experience", id)} onUpdate={(id, field, value) => updateEntry("experience", id, field, value)}/>
        <EditorSection title="Selected achievements (optional)"><Textarea maxLength={3000} onChange={(event) => set("achievements", event.target.value)} placeholder={"Precepted 12 newly hired nurses through unit orientation\nReduced medication-administration documentation errors by 18%"} rows={5} value={content.achievements}/><p className="text-xs leading-5 text-muted-foreground">Use measurable outcomes, improvements, recognition, presentations, or quality initiatives.</p></EditorSection>
        <EntriesEditor entries={content.education} label="Education and clinical training" onAdd={() => addEntry("education")} onRemove={(id) => removeEntry("education", id)} onUpdate={(id, field, value) => updateEntry("education", id, field, value)}/>
        <div className="grid gap-5 sm:grid-cols-2"><EditorSection title="Professional affiliations (optional)"><Textarea maxLength={3000} onChange={(event) => set("affiliations", event.target.value)} placeholder="American Association of Critical-Care Nurses" rows={4} value={content.affiliations}/></EditorSection><EditorSection title="Languages (optional)"><Textarea maxLength={1500} onChange={(event) => set("languages", event.target.value)} placeholder={"English — Fluent\nSpanish — Conversational"} rows={4} value={content.languages}/></EditorSection></div>
      </form>
      <ResumePreview content={content} templateKey={templateKey}/>
    </div>
  </div>
}

function TemplatePoint({ children, title }: { children: React.ReactNode; title: string }) { return <div className="flex gap-3"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-primary"/><p><strong className="block font-semibold text-foreground">{title}</strong>{children}</p></div> }
function EditorSection({ children, title }: { children: React.ReactNode; title: string }) { return <Card className="bg-white"><CardContent className="grid gap-4 p-5"><h2 className="font-semibold">{title}</h2>{children}</CardContent></Card> }
function Field({ children, label }: { children: React.ReactNode; label: string }) { return <label className="grid gap-2 text-sm font-medium">{label}{children}</label> }

function templatePreviewClass(template: CvTemplateKey) {
  return ({ clinical_sidebar: "bg-slate-800", modern_blue_header: "bg-sky-500", executive_timeline: "bg-slate-600", accent_column: "bg-amber-400", two_column_professional: "bg-indigo-700", classic_medical: "bg-slate-900", navy_sidebar: "bg-[#285a7c]" } as Record<CvTemplateKey, string>)[template]
}

function EntriesEditor({ entries, label, onAdd, onRemove, onUpdate }: { entries: ResumeEntry[]; label: string; onAdd: () => void; onRemove: (id: string) => void; onUpdate: (id: string, field: keyof ResumeEntry, value: string) => void }) {
  return <EditorSection title={label}>{entries.map((entry, index) => <div className="grid gap-3 rounded-xl border p-4" key={entry.id}><div className="flex items-center justify-between"><strong className="text-sm">Entry {index + 1}</strong><Button aria-label={`Remove ${label} entry ${index + 1}`} onClick={() => onRemove(entry.id)} size="icon" type="button" variant="ghost"><Trash2/></Button></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Role or degree"><Input maxLength={120} onChange={(event) => onUpdate(entry.id, "title", event.target.value)} value={entry.title}/></Field><Field label="Organization or school"><Input maxLength={120} onChange={(event) => onUpdate(entry.id, "organization", event.target.value)} value={entry.organization}/></Field><Field label="Location"><Input maxLength={120} onChange={(event) => onUpdate(entry.id, "location", event.target.value)} value={entry.location}/></Field><Field label="Dates"><div className="grid grid-cols-2 gap-2"><Input aria-label="Start date" maxLength={30} onChange={(event) => onUpdate(entry.id, "startDate", event.target.value)} placeholder="Jan 2024" value={entry.startDate}/><Input aria-label="End date" maxLength={30} onChange={(event) => onUpdate(entry.id, "endDate", event.target.value)} placeholder="Present" value={entry.endDate}/></div></Field></div><Field label="Achievements and responsibilities"><Textarea maxLength={4000} onChange={(event) => onUpdate(entry.id, "details", event.target.value)} placeholder="One action-and-result bullet per line. Start with a strong verb and quantify impact where possible." rows={5} value={entry.details}/></Field></div>)}<Button disabled={entries.length >= 20} onClick={onAdd} type="button" variant="outline"><Plus/>Add entry</Button></EditorSection>
}

function ResumePreview({ content, templateKey }: { content: ResumeContent; templateKey: CvTemplateKey }) {
  const section = (title: string, children: React.ReactNode, show: boolean) => show && <section className="mt-5 break-inside-avoid"><h2 className="border-b border-slate-400 pb-1 text-[11px] font-bold tracking-[0.12em] uppercase">{title}</h2><div className="mt-2">{children}</div></section>
  const bulletList = (value: string) => <ul className="list-disc space-y-1 pl-5">{lines(value).map((line, index) => <li key={`${line}-${index}`}>{line}</li>)}</ul>
  const entryList = (items: ResumeEntry[]) => <div className="grid gap-4">{items.map((entry) => <div className="break-inside-avoid" key={entry.id}><div className="flex justify-between gap-3"><div><h3 className="font-bold">{entry.title || "Role or degree"}</h3><p>{[entry.organization, entry.location].filter(Boolean).join(" · ")}</p></div><p className="shrink-0 text-xs">{[entry.startDate, entry.endDate].filter(Boolean).join(" – ")}</p></div>{lines(entry.details).length > 0 && bulletList(entry.details)}</div>)}</div>
  const credentialLines = [content.licenses, content.certifications].flatMap(lines)
  const isSidebar = ["clinical_sidebar", "navy_sidebar", "accent_column"].includes(templateKey)
  const isBlue = ["modern_blue_header", "two_column_professional", "navy_sidebar"].includes(templateKey)
  const headerClass = isBlue ? "bg-[#285a7c] text-white" : templateKey === "accent_column" ? "border-t-8 border-amber-400" : "border-b-2 border-slate-950"
  const identity = <><h1 className="text-2xl font-bold tracking-tight">{content.fullName || "Your Name"}</h1>{content.professionalHeadline && <p className="mt-1 font-semibold opacity-85">{content.professionalHeadline}</p>}<p className="mt-2 text-xs">{[content.cityState, content.phone, content.email].filter(Boolean).join(" · ")}{content.linkedin && <><span> · </span><a className="underline" href={content.linkedin.startsWith("http") ? content.linkedin : `https://${content.linkedin}`} rel="noreferrer" target="_blank">LinkedIn</a></>}</p></>
  const details = <>{section("Professional Summary", <p className="whitespace-pre-wrap">{content.summary}</p>, Boolean(content.summary))}{section("Professional Experience", entryList(content.experience), content.experience.length > 0)}{section("Selected Achievements", bulletList(content.achievements), Boolean(content.achievements))}{section("Education & Clinical Training", entryList(content.education), content.education.length > 0)}{section("Professional Affiliations", bulletList(content.affiliations), Boolean(content.affiliations))}</>
  const sideDetails = <>{section("Licensure & Certifications", <ul className="list-disc space-y-1 pl-5">{credentialLines.map((line, index) => <li key={`${line}-${index}`}>{line}</li>)}</ul>, credentialLines.length > 0)}{section("Core Clinical Skills", <p>{lines(content.skills).join(" · ")}</p>, Boolean(content.skills))}{section("Languages", <p>{lines(content.languages).join(" · ")}</p>, Boolean(content.languages))}</>
  return <article className={`resume-document sticky top-4 min-h-[11in] bg-white text-[10.5pt] leading-[1.35] text-slate-950 shadow-sm ring-1 ring-slate-200 print:static print:min-h-0 print:shadow-none print:ring-0 ${isSidebar ? "grid grid-cols-[32%_68%]" : "p-[0.55in]"}`}><div className={isSidebar ? `p-7 ${isBlue ? "bg-[#285a7c] text-white" : "bg-slate-800 text-white"}` : "hidden"}>{isSidebar && identity}{isSidebar && sideDetails}</div><div className={isSidebar ? "p-7" : ""}>{!isSidebar && <header className={`pb-3 ${headerClass} ${isBlue ? "-mx-[0.55in] -mt-[0.55in] px-[0.55in] pt-[0.45in]" : ""} ${templateKey === "executive_timeline" ? "text-left" : "text-center"}`}>{identity}</header>}{details}{!isSidebar && sideDetails}</div><style jsx global>{`@media print { @page { size: letter; margin: .35in; } body { background: white !important; } body * { visibility: hidden; } .resume-document, .resume-document * { visibility: visible; } .resume-document { position: absolute; inset: 0; width: 100%; font-family: Arial, sans-serif; } }`}</style></article>
}
